---
- name: Install home server appliances
  hosts: home
  gather_facts: true
  tasks:
    - name: Get current user
      command: whoami
      register: whoami_output

    - name: Register installation_user
      set_fact:
        installation_user: "{{ whoami_output.stdout }}"

    - name: Register Host IP
      set_fact:
        host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Get docker network information
      community.docker.docker_network_info:
        name: "{{ traefik_network_name }}"
      register: result

    - name: Create docker network for traefik and the rest of services
      when: not result.exists
      community.docker.docker_network:
        name: "{{ traefik_network_name }}"

    - name: Run Traefik
      include_tasks: tasks/traefik.yml

    - name: Run jellyfin
      include_tasks: tasks/jellyfin.yml
