---
- name: Install home server appliances
  hosts: home
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/stacks.yml
  tasks:
    - name: Get docker network information
      community.docker.docker_network_info:
        name: "{{ docker.network_name }}"
      register: result

    - name: Create docker network for traefik and the rest of services
      when: not result.exists
      community.docker.docker_network:
        name: "{{ docker.network_name }}"

    - name: Prepare Stacks
      include_tasks: "tasks/stacks/{{ _stack.key }}.yml"
      loop: "{{ stacks|dict2items }}"
      loop_control:
        loop_var: _stack

    - name: Restart stack containers if needed
      include_tasks: tasks/tools/compose.yml
      loop: "{{ stacks|dict2items }}"
      loop_control:
        loop_var: _stack
