---
- name: Install home server appliances
  hosts: home
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/stacks.yml
  vars:
    host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    stack_filter: "{{ lookup('env', 'INCLUDE_TASK')|default('')|trim }}"
    stack_list: "{{ stacks|dict2items }}"
  tasks:
    - include_vars:
        file: secret.yml
        name: secrets

    - name: Get list of stacks to install
      when: stack_filter != ""
      set_fact:
        stack_list: "{{ stack_list | selectattr('key', 'equalto', stack_filter) | list }}"

    - name: Get docker network information
      community.docker.docker_network_info:
        name: "{{ docker.network_name }}"
      register: result

    - name: Create docker network for traefik and the rest of services
      when: not result.exists
      community.docker.docker_network:
        name: "{{ docker.network_name }}"

    - name: Prepare Stacks
      include_tasks: tasks/tools/stacks.yml
      loop: "{{ stack_list }}"
      loop_control:
        loop_var: _stack

    - name: Restart stack containers if needed
      include_tasks: tasks/tools/compose.yml
      loop: "{{ stack_list }}"
      loop_control:
        loop_var: _stack

    - name: Install the git server
      when: stack_filter == ""
      include_tasks: tasks/tools/git.yml
    
