---
- name: Install home server appliances
  hosts: home
  gather_facts: true
  tasks:
    - include_vars: vars/main.yml

    - name: Get current user
      command: whoami
      register: whoami_output

    - name: Register installation_user
      set_fact:
        installation_user: "{{ whoami_output.stdout }}"

    - name: Register Host IP
      set_fact:
        host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Get docker network information
      community.docker.docker_network_info:
        name: "{{ stacks.traefik.network_name }}"
      register: result

    - name: Create docker network for traefik and the rest of services
      when: not result.exists
      community.docker.docker_network:
        name: "{{ stacks.traefik.network_name }}"

    - name: Prepare Traefik
      include_tasks: tasks/traefik.yml

    - name: Prepare Jellyfin
      include_tasks: tasks/jellyfin.yml

    - name: Prepare Pihole
      include_tasks: tasks/pihole.yml

    - name: Prepare Prometheus
      include_tasks: tasks/prometheus.yml
