---
- name: Provision home server
  hosts: home
  gather_facts: false   # needs python
  tasks:
    - name: Include main variables
      ansible.builtin.include_vars: vars/main.yml

    - name: Include secrets
      ansible.builtin.include_vars:
        file: secret.yml
        name: secrets

    - name: Install needed software
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Create users
      ansible.builtin.include_tasks: tasks/users.yml

    - name: Mount shares
      ansible.builtin.include_tasks: tasks/shares.yml
    