---
- name: Provision home server
  hosts: home
  gather_facts: false   # needs python
  tasks:
    - include_vars: vars/main.yml
    - include_vars:
        file: secret.yml
        name: secrets

    - name: Install needed software
      include_tasks: tasks/packages.yml

    - name: Create users
      include_tasks: tasks/users.yml

    - name: Mount shares
      include_tasks: tasks/shares.yml
