---
- name: Provision home server
  hosts: home
  gather_facts: false   # needs python
  tasks:
    - name: Install needed software
      include_tasks: tasks/packages.yml

    - name: Create users
      include_tasks: tasks/users.yml

    - name: Mount shares
      include_tasks: tasks/nfs.yml
