---
- name: Create jellyfin directory
  become: true
  file:
    state: directory
    path: "{{ jellyfin_folder }}"
    owner: "{{ installation_user }}"
    mode: 0777

- name: Touch log config file
  copy:
    src: "files/jellyfin/logging.default.json"
    dest: "{{ nfs_jellyfin_config }}/"
    force: false
    owner: "{{ installation_user }}"
    mode: 0777

- name: Touch log watches file
  become: true
  copy:
    content: ""
    dest: /etc/sysctl.d/40-max-user-watches.conf
    force: false

- name: Enable real-time monitoring of libraries
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/40-max-user-watches.conf
    regex: "fs.inotify.max_user_watches.*"
    line: "fs.inotify.max_user_watches=524288"
  register: watches_config

- name: Reload services
  when: watches_config.changed
  become: true
  raw: sysctl --system

- name: Render jellyfin files
  template:
    src: "files/jellyfin/{{ item }}.j2"
    dest: "{{ jellyfin_folder }}/{{ item }}"
  loop:
    - docker-compose.yml
  register: jellyfin_files

- name: Stop previous containers
  when: jellyfin_files.changed
  community.docker.docker_compose:
    project_src: "{{ jellyfin_folder }}"
    state: absent

- name: Create and start services
  when: jellyfin_files.changed
  community.docker.docker_compose:
    project_src: "{{ jellyfin_folder }}"
