---
- name: Create jellyfin directory
  become: true
  file:
    state: directory
    path: "{{ stacks.jellyfin.folder }}"
    owner: 1000
    group: 1000
    mode: 0777

- name: Touch log watches file
  become: true
  copy:
    content: ""
    dest: /etc/sysctl.d/40-max-user-watches.conf
    force: false

- name: Enable real-time monitoring of libraries
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/40-max-user-watches.conf
    regex: "fs.inotify.max_user_watches.*"
    line: "fs.inotify.max_user_watches=524288"
  register: watches_config

- name: Reload services
  when: watches_config.changed
  become: true
  raw: sysctl --system

- name: Render jellyfin files
  template:
    src: "files/jellyfin/{{ item }}.j2"
    dest: "{{ stacks.jellyfin.folder }}/{{ item }}"
  loop:
    - docker-compose.yml
  register: jellyfin_files

- name: Get current status
  community.docker.docker_compose:
    project_src: "{{ stacks.jellyfin.folder }}"
    build: false
  register: output

- name: Stop previous jellyfin containers
  when: jellyfin_files.changed and output.services.jellyfin.jellyfin.state.running
  community.docker.docker_compose:
    project_src: "{{ stacks.jellyfin.folder }}"
    state: absent
  register: output

- name: Create and start services
  when: jellyfin_files.changed or output.changed
  community.docker.docker_compose:
    project_src: "{{ stacks.jellyfin.folder }}"
