---
- name: Create mount points
  become: true
  file:
    path: "{{ item.mount_point }}"
    state: directory
  loop:
    - "{{ nfs_movies }}"
    - "{{ nfs_shows }}"
    - "{{ nfs_jellyfin }}"

- name: Change config folder permissions
  become: true
  ansible.builtin.file:
    path: "{{ nfs_jellyfin_config }}"
    state: directory
    recurse: true
    owner: 1000
    group: 1000

- name: Add mounts to /etc/fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regex: ".*{{ item.mount_point }}.*"
    line: |
      {{ nfs_shares_root }}:{{ item.folder }} {{ item.mount_point }}  nfs noauto,x-systemd.automount,_netdev,timeo=10,x-systemd.ilde-timeout=60
  loop:
    - "{{ nfs_movies }}"
    - "{{ nfs_shows }}"
    - "{{ nfs_jellyfin }}"
  register: fstab_mounts

- name: Reload services
  when: fstab_mounts.changed
  become: true
  raw: systemctl daemon-reload

- name: Restart remote FS
  when: fstab_mounts.changed
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: remote-fs.target
