---
- name: Raw-install Python3
  raw: pacman --noconfirm -S python3 python-pip

- name: Docker install
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker
    - docker-compose

- name: Python packages for Docker
  raw: "pip install {{ item }}"
  loop:
    - "setuptools>=65.6.0"
    - "docker>=6.0.0"
    - "docker-compose>=1.29.2"
    - "PyYAML>=5.4.0"

- name: Enable systemd service
  ansible.builtin.systemd:
    enabled: true
    name: docker

- name: Start systemd service
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Install NFS client
  pacman:
    name: nfs-utils
    state: present
