---
- name: Check for python
  raw: "command -v python"
  register: python_output

- set_fact:
    python_installed: "{{ not python_output.stdout }}"

- name: Raw-install Python3
  when: not python_installed
  raw: pacman --noconfirm -S python3 python-pip python-pipx
  become: true

- name: Python packages for Pip
  raw: "pip install --break-system-packages '{{ item }}'"
  loop:
    - "setuptools>=65.6.0"

- name: Python packages for Docker
  pip:
    extra_args: --user --break-system-packages
    name:
      - Docker
      - PyYAML

- name: Install my packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker
    - docker-compose
    - cifs-utils
    - wget
    - unzip
    - p7zip
    - git
    - rsync
    - ntp

- name: Enable services
  become: true
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: "{{ item }}"
  loop:
    - ntpd
    - docker
