---
- name: Check for python
  raw: "command -v python3"
  register: python_output

- name: Exit without python
  when: not python_output.stdout
  fail:
    msg: "Python 3 must be installed in the system"

- name: Install my packages
  become: true
  package:
    state: present@|@
    name:
      - docker
      - python3-pip
      - python3-dev
      - python3-docker
      - python3-yaml
      - docker-compose
      - cifs-utils
      - wget
      - unzip
      - p7zip
      - rsync
      - ntp
      - tree

- name: Enable services
  become: true
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: "{{ item }}"
  loop:
    - ntpd
    - docker
