---
- name: "({{ _stack.key }}) Set compose variables for stack"
  set_fact:
    compose_folder: "{{ _stack.value.folder }}"
    compose_files_changed: "{{ lookup('vars', '{{ _stack.key }}_files').changed }}"
    compose_recreate: smart

- name: "({{ _stack.key }}) Set recreation to 'always' if files have changed"
  when: compose_files_changed
  set_fact:
    compose_recreate: always

- name: "({{ _stack.key }}) Create and start stack's containers"
  community.docker.docker_compose:
    project_src: "{{ compose_folder }}"
    recreate: "{{ compose_recreate }}"

- name: "({{ _stack.key }}) Clear compose variables for stack"
  set_fact:
    compose_folder:
    compose_files_changed:
    compose_recreate:
