---
- name: "Set compose variables for '{{ _stack.key }}' stack"
  set_fact:
    compose_folder: "{{ _stack.value.folder }}"
    compose_files_changed: "{{ lookup('vars', '{{ _stack.key }}_files').changed }}"
    compose_recreate: smart

- name: "Set recreation to 'always' if files have changed"
  when: compose_files_changed
  set_fact:
    compose_recreate: always

- name: "Create and start '{{ _stack.key }}' stack's containers"
  community.docker.docker_compose:
    project_src: "{{ compose_folder }}"
    recreate: "{{ compose_recreate }}"

- name: "Clear compose variables for '{{ _stack.key }}' stack"
  set_fact:
    compose_folder:
    compose_files_changed:
    compose_recreate:
