---
- name: Get some stack facts
  set_fact:
    stack_disabled: "{{ _stack.value.disabled | default(false) | bool }}"

- name: Report if stack is disabled
  when: stack_disabled
  debug:
    msg: "Stack {{ _stack.key }} is disabled, not installing"

- name: Install enabled stack
  when: not stack_disabled
  include_tasks: tasks/tools/install_enabled_stack.yml

