---
- name: Touch log watches file
  become: true
  copy:
    content: ""
    dest: /etc/sysctl.d/40-max-user-watches.conf
    force: false


- name: Create and give permissions to /dev/shm/jf-transcodes directory
  become: true
  ansible.builtin.file:
    path: /dev/shm/jf-transcodes
    state: directory
    mode: '0777'

- name: Enable real-time monitoring of libraries
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/40-max-user-watches.conf
    regex: "fs.inotify.max_user_watches.*"
    line: "fs.inotify.max_user_watches=524288"
  register: watches_config

- name: Reload services
  when: watches_config.changed
  become: true
  raw: sysctl --system
