---
# Disable port 53 in host so we can use pihole: https://github.com/pi-hole/docker-pi-hole/#running-pi-hole-docker
- name: Disable DNS port in host
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regex: '.*DNSStubListener.*'
    line: DNSStubListener=no
  register: resolv_file

- name: Delete system resolv.conf
  when: resolv_file.changed
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/resolv.conf

- name: Symlink resolve file to systemd
  when: resolv_file.changed
  become: true
  ansible.builtin.file:
    state: link
    src: /etc/systemd/resolved.conf
    dest: /etc/resolv.conf

- name: Restart systemd-resolved
  when: resolv_file.changed
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: systemd-resolved
