---
- name: Install needed software
  hosts: home
  gather_facts: no
  become: yes
  tasks:
    - name: Raw-install Python3
      raw: pacman --noconfirm -S python3

    - name: Full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Docker install
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose

    - name: Enable systemd service
      ansible.builtin.systemd:
        enabled: yes
        name: docker

    - name: Start systemd service
      ansible.builtin.systemd:
        state: started
        name: docker
