---
- name: "Create {{ _stack.key }} directory"
  become: true
  file:
    state: directory
    path: "{{ _stack.value.folder }}"
    owner: 1000
    group: 1000
    mode: 0777

# TODO: iterate over a set list of files
- name: "Render {{ _stack.key }} files"
  template:
    src: "files/{{ _stack.key }}/{{ item }}.j2"
    dest: "{{ _stack.value.folder }}/{{ item }}"
  loop: "{{ _stack.value.templates|default([]) }}"
  register: _stack_files

#- name: "Get extra tasks for {{ _stack.key }}"
#  set_fact:
#    tasks_file: "tasks/stacks/{{ _stack.key }}.yml"
#
#- name: Include tasks only if one of the files exists, otherwise skip
#  ansible.builtin.include_tasks: '{{ tasks_file }}'
# when: tasks_file is file

- name: register flag of changed files if tasks file has not done it
#  when: not tasks_file is file
  set_fact:
    "{{ _stack.key }}_files": "{{ _stack_files }}"
