---
- name: Create Prometheus directories
  become: true
  file:
    state: directory
    path: "{{ item }}"
    owner: 1000
    group: 1000
    mode: 0777
  loop:
    - "{{ stacks.prometheus.folder }}"
    - "{{ stacks.prometheus.folder }}/etc"
    - "{{ stacks.prometheus.folder }}/data"

- name: Render Prometheus files
  template:
    src: "files/prometheus/{{ item }}.j2"
    dest: "{{ stacks.prometheus.folder }}/{{ item }}"
  loop:
    - docker-compose.yml
    - etc/alert.rules
    - etc/prometheus.yml
  register: prometheus_files
